services:
  bot_api_server:
    build: ./src
    container_name: bot_api
    networks:
      - bot_services
      - inner_network
    environment:
      TZ: Asia/Tashkent
      POSTGRES_URL: host=postgres user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_INNER_PORT sslmode=disable
      REDIS_PORT: $REDIS_PORT
      BOT_TOKEN: $BOT_TOKEN
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_TTL: $REDIS_TTL
      GRPC_PORT: $GRPC_PORT
    ports:
    - "50051:50051"
networks:
  bot_services:
    external: true
  inner_network:
