services:
  redis:
    image: redis:7.4-alpine
    container_name: redis-container
    networks:
      - inner_network
    command: sh -c "exec redis-server --requirepass \"$REDIS_PASSWORD\" --save '' --appendonly no"
    volumes:
      - ./redis_data:/data
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  server:
    build: ./src
    container_name: bot_api
    networks:
      - postgres_network
      - inner_network
    environment:
      TZ: Asia/Tashkent
      POSTGRES_URL: host=postgres user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_INNER_PORT sslmode=disable
      REDIS_PORT: $REDIS_PORT
      BOT_TOKEN: $BOT_TOKEN
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_TTL: $REDIS_TTL

networks:
  postgres_network:
    external: true
  inner_network: